services:
  jaeger:
    image: jaegertracing/all-in-one:1.69.0
    platform: linux/arm64
#    container_name: jaeger
    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_ENABLED=true
      - COLLECTOR_OTLP_HTTP_ENABLED=true
      - LOG_LEVEL=debug
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "14268:14268"
#      - "9411:9411"
